### ISSUE TITLE
Maintainer wanted

### ISSUE THREAD

**Issue by jsguy** [jsguy/ga-api#9]
Hi there!

This project is looking for maintainer(s).

I am unable to spend time on this project, and seeing people are still depending on this project, I'd like to hand over the reins to someone who might be interested in maintaining it.

For now only pull requests of external contributors are being reviewed, accepted and welcomed. No more bug fixes or new features will be implemented.

If you are interested, please comment on this issue.

**Comment by HugoPoi** [comment]
I'm interested !

**Comment by jsguy** [comment]
Awesome - I've added you - welcome to the team!

**Comment by gunheekim90** [comment]
i'm interested too!

**Comment by jsguy** [comment]
Great - I've added you, welcome to the team!

**Comment by jimmywarting** [comment]
I'd be willing to take up maintainership for this project. My company is looking to use this project, I'm a core team member of the popular node-fetch package since the very first besinning and takes care of a number of other popular open source project.
I know a thing or two about open source and making sure it's harmful and well documented and safe

That being said, I have had a fascination of getting things modernized. My motivations are not to prioritize the needs of my company over the needs of the community. Looking through the issues, I think that I could help with answering the questions people have or looking into (and potentially fixing) the problems that are presented.

If it's alright with you then I would like to get full maintainership of npm package and that the github is transfered to my account along with all the issues/PR that comes with it

Just let me know 👍

**Comment by jsguy** [comment]
@jimmywarting that sounds good, glad the project will go to a good home - transfer request sent.
